name: CI MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "Project/wine-quality.csv"
  TARGET_VAR: "quality"
  ALPHA: 0.5
  L1_RATIO: 0.5
  RANDOM_STATE: 42

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      # BENER
      # Setup Python 3.11.13
      - name: Set up Python 3.11.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.13

      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL
          python --version
          pip --version

      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./Project/requirements.txt

      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          cd Project
          mlflow run . --env-manager=local
